# generated by datamodel-codegen:
#   filename:  EventBase.json
#   timestamp: 2022-05-25T12:05:48+00:00

from __future__ import annotations

from datetime import datetime
from typing import Any, Optional

from pydantic import BaseModel, Field


class EventBase(BaseModel):
    event_type: str = Field(..., title='Event Type')
    user_id: str = Field(..., title='User Id')
    event_timestamp: datetime = Field(..., title='Event Timestamp')
    event_payload: Any = Field(..., title='Event Payload')
