# generated by datamodel-codegen:
#   filename:  PageView.json
#   timestamp: 2022-05-28T11:12:55+00:00

from __future__ import annotations

from pydantic import UUID4, BaseModel, Field


class PageView(BaseModel):
    doc_id: UUID4 = Field(..., title='Doc Id')
    destination_bq: str = Field(..., title='Destination Bq')
