# generated by datamodel-codegen:
#   filename:  PageViewPayload.json
#   timestamp: 2022-05-25T12:06:51+00:00

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, Field


class PageViewPayload(BaseModel):
    doc_id: UUID = Field(..., title='Doc Id')
    destination_bq: str = Field(..., title='Destination Bq')
